void exitchoice(double round);
int main();
int add(double round);
void returnReturnRound(double round);
void sub(double round);
void multiply(double round);
void divide(double round);
void remain(int round);
void increment(double round);
void decrement(double round);
void unaryAdd(double round);