void exitchoice(double round);
int main();
int add(double round);
void returnReturnRound(double round);
void sub(double round);
void multiply(double round);
void divide(double round);
void remain(int round);
void increment(double round);
void decrement(double round);
void unaryAdd(double round);
void roundMode(double round2);
void roundCeil(double round2);
void roundFlr(double round2);
void divR(int round);
void setNumber(double round);
void multinumchoice(std::string param1, double num1, double num2);
void Pow(double round);